import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleAnalytics as GA } from '@next/third-parties/google'
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {/*<GA gaId="G-391BN8089P" />*/}
    </html>
  );
}
